# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a40775fc32efc7b187d7d48d8ec1eb4692016b9868baff278a74aa2b62103efb1d49d2dfb077d96376e58385ba06f4caf96eec7723f53110cbbb255028a360a

test:
  secret_key_base: 45d6815d25136dfe59bfb68116dc51a848d5dc1971dca849125c0d00da928d56307238de5250e40dac80bb120653345fa50149b755cf28002a45dea6359d7a51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
